### ISSUE TITLE
SSL Error recovery behavior

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/aiokraken#9]
This happens sometimes : 
```
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-12-d2e8d2446d43> in async-def-wrapper()
     27     # convert what we want to draw to numeric to please mpl
     28     ohlc_df.dataframe.close = pd.to_numeric(ohlc_df.dataframe.close)
---> 29     #ohlc_df.time = pd.to_datetime(ohlc_df.time, unit='s')
     30     ohlc_df.dataframe.plot(x='time', y='close')
     31 

/opt/Projects/aiokraken/aiokraken/rest/client.py in ohlc(self, pair)
     49         kt = self.server.ohlc(pair=pair)   # returns the request to be made for this API.)
     50         try:  # TODO : pass protocol & host into the request url in order to have it displayed when erroring !
---> 51             async with self.session.post(self.protocol + self.server.url + kt.urlpath, headers=kt.headers, data=kt.data) as response:
     52 
     53                 return await kt(response)

~/.local/share/virtualenvs/aiokraken-bMbyeTfo/lib/python3.7/site-packages/aiohttp/client.py in __aenter__(self)
   1011 
   1012     async def __aenter__(self) -> _RetType:
-> 1013         self._resp = await self._coro
   1014         return self._resp
   1015 

~/.local/share/virtualenvs/aiokraken-bMbyeTfo/lib/python3.7/site-packages/aiohttp/client.py in _request(self, method, str_or_url, params, data, json, cookies, headers, skip_auto_headers, auth, allow_redirects, max_redirects, compress, chunked, expect100, raise_for_status, read_until_eof, proxy, proxy_auth, timeout, verify_ssl, fingerprint, ssl_context, ssl, proxy_headers, trace_request_ctx)
    503                             resp = await req.send(conn)
    504                             try:
--> 505                                 await resp.start(conn)
    506                             except BaseException:
    507                                 resp.close()

~/.local/share/virtualenvs/aiokraken-bMbyeTfo/lib/python3.7/site-packages/aiohttp/client_reqrep.py in start(self, connection)
    846                 # read response
    847                 try:
--> 848                     message, payload = await self._protocol.read()  # type: ignore  # noqa
    849                 except http.HttpProcessingError as exc:
    850                     raise ClientResponseError(

~/.local/share/virtualenvs/aiokraken-bMbyeTfo/lib/python3.7/site-packages/aiohttp/streams.py in read(self)
    590             self._waiter = self._loop.create_future()
    591             try:
--> 592                 await self._waiter
    593             except (asyncio.CancelledError, asyncio.TimeoutError):
    594                 self._waiter = None

CancelledError: 

SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fd6fb806278>
transport: <_SelectorSocketTransport fd=62 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

```

We should investigate and attempt to recover from this (by re-initiating a connection for example...)

**Comment by asmodehn** [comment]
This is currently avoided by re attempting to send a request.
